{
 "title": "CheckFritzbox",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "measurement",
    "query": "SHOW SERIES WHERE \"topic\"='fb_tr069'"
   },
   {
    "name": "rp",
    "query": "select time,rp from forever.grafana_rp where time > now() - ${__from}ms order by time asc limit 1"
   },
   {
    "name": "box",
    "query": "SHOW TAG VALUES FROM \"$measurement\" WITH KEY = \"box\""
   },
   {
    "name": "interface",
    "query": "SHOW TAG VALUES FROM \"$measurement\" WITH KEY = \"interface\""
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "name",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewDescription" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    }
   ]
  },
  {
   "title": "Uplink vDSL speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Up",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewDownstreamCurrRate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wan" }
     ]
    }
   ]
  },
  {
   "title": "Downlink vDSL",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Down",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewUpstreamCurrRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wan" }
     ]
    }
   ]
  },
  {
   "title": "IoT clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewTotalAssociations" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wlanGuest" }
     ]
    }
   ]
  },
  {
   "title": "Traffic analysis",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 0 },
   "targets": [
    {
     "alias": "Down",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       {
        "params": [
         "v_NewX_AVM_DE_TotalBytesReceived64"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    },
    {
     "alias": "Down",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewX_AVM_DE_TotalBytesSent64" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "uptime",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewUpTime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    }
   ]
  },
  {
   "title": "Connected vDSL",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "uptime",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewUptime" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wan" }
     ]
    }
   ]
  },
  {
   "title": "Up ",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewX_AVM_DE_TotalBytesSent64" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wan" }
     ]
    }
   ]
  },
  {
   "title": "Down",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       {
        "params": [
         "v_NewX_AVM_DE_TotalBytesReceived64"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wan" }
     ]
    }
   ]
  },
  {
   "title": "2.4ghz clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "interface" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewTotalAssociations" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wlan24" }
     ]
    }
   ]
  },
  {
   "title": "IPv4",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "targets": [
    {
     "alias": "IPv4",
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"v_NewExternalIPAddress\") FROM \"default\"./^$measurement$/ WHERE (\"box\" =~ /^$box$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "v_NewExternalIPAddress" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    }
   ]
  },
  {
   "title": "IPv6",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "targets": [
    {
     "alias": "IPv6",
     "measurement": "/^$measurement$/",
     "query": "SELECT last(\"v_NewExternalIPv6Address\") FROM \"default\"./^$measurement$/ WHERE (\"box\" =~ /^$box$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "v_NewExternalIPv6Address" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    }
   ]
  },
  {
   "title": "Up (10m avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewX_AVM_DE_TotalBytesSent64" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "Down (10m avg)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "10m" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       {
        "params": [
         "v_NewX_AVM_DE_TotalBytesReceived64"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1s" ], "type": "non_negative_derivative" },
       { "params": [ "*8" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "5ghz clients",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewTotalAssociations" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wlan5" }
     ]
    }
   ]
  },
  {
   "title": "Last connection error",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewLastConnectionError" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    }
   ]
  },
  {
   "title": "Downstream noise margin",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface",
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewDownstreamNoiseMargin" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    }
   ]
  },
  {
   "title": "DHCP leases",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewHostNumberOfEntries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    }
   ]
  },
  {
   "title": "DECT phones",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewNumberOfEntries" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "dect" }
     ]
    }
   ]
  },
  {
   "title": "VOIP connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewNumberOfNumbers" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "voip" }
     ]
    }
   ]
  },
  {
   "title": "Last day up",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewX_AVM_DE_TotalBytesSent64" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Last day down",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "1d" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       {
        "params": [
         "v_NewX_AVM_DE_TotalBytesReceived64"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "2.4ghz channel",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewChannel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wlan24" }
     ]
    }
   ]
  },
  {
   "title": "5ghz channel",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewChannel" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "wlan5" }
     ]
    }
   ]
  },
  {
   "title": "Possible rates vDSL",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Kbits" } },
   "targets": [
    {
     "alias": "Upstream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewUpstreamMaxRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    },
    {
     "alias": "Downstream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewDownstreamMaxRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "10" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    }
   ]
  },
  {
   "title": "Pakets",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 6, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_interface up",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewTotalPacketsReceived" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
     ]
    },
    {
     "alias": "$tag_interface down",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewTotalPacketsSent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=", "value": "0896D74ACAA0" },
      { "condition": "AND", "key": "interface", "operator": "=~", "value": "/^$interface$/" }
     ]
    }
   ]
  },
  {
   "title": "WLAN clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_interface",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewTotalAssociations" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    }
   ]
  },
  {
   "title": "DSL rate ",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "alias": "Downstream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewByteReceiveRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    },
    {
     "alias": "Upstream",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewByteSendRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    }
   ]
  },
  {
   "title": "Hourly Diskstation Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "from diskstation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewTotalBytesReceived" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "lan" }
     ]
    },
    {
     "alias": "to diskstation",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewTotalBytesSent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" },
      { "condition": "AND", "key": "interface", "operator": "=", "value": "lan" }
     ]
    }
   ]
  },
  {
   "title": "Hourly DSL Traffic",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "Downstream",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       {
        "params": [
         "v_NewX_AVM_DE_TotalBytesReceived64"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    },
    {
     "alias": "Upstream",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewX_AVM_DE_TotalBytesSent64" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       {
        "params": [],
        "type": "non_negative_difference"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    }
   ]
  },
  {
   "title": "Noise profile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Upstream noise",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewUpstreamNoiseMargin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    },
    {
     "alias": "Downstream noise",
     "groupBy": [
      { "params": [ "1h" ], "type": "time" },
      { "params": [ "interface" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "v_NewDownstreamNoiseMargin" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "box", "operator": "=~", "value": "/^$box$/" }
     ]
    }
   ]
  }
 ]
}