{
 "title": "Fritzbox",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "measurement",
    "query": "SHOW SERIES WHERE \"topic\"='docinfo'"
   },
   {
    "name": "field",
    "query": "SHOW FIELD KEYS from \"fb\""
   },
   {
    "name": "frequency",
    "query": "SHOW TAG VALUES FROM \"fb\" WITH KEY=\"frequency\""
   }
  ]
 },
 "panels": [
  {
   "title": "$field",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_frequency]] MHz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "frequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fb",
     "query": "SELECT mean($field) FROM /^$measurement$/ WHERE (\"topic\" = 'docinfo' AND \"mode\" = 'Ds' AND frequency =~ /^$frequency$/) AND $timeFilter GROUP BY time($__interval), \"frequency\" fill(null)",
     "select": [
      [
       { "params": [ "/^$field$/" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "docinfo" },
      { "condition": "AND", "key": "mode", "operator": "=", "value": "Ds" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate nonCorrectable",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_frequency]] MHz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "frequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fb",
     "query": "SELECT non_negative_derivative(mean(\"nonCorrErrors\"), 5m) FROM  /^$measurement$/ WHERE (\"topic\" = 'docinfo' AND \"mode\" = 'Ds' AND frequency =~ /^$frequency$/) AND $timeFilter GROUP BY time($__interval), \"frequency\" fill(null)",
     "select": [
      [
       { "params": [ "nonCorrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "docinfo" },
      { "condition": "AND", "key": "mode", "operator": "=", "value": "Ds" }
     ]
    }
   ]
  },
  {
   "title": "Error Rate Correctable",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "[[tag_frequency]] MHz",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "frequency" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fb",
     "query": "SELECT non_negative_derivative(mean(\"corrErrors\"), 5m) FROM  /^$measurement$/ WHERE (\"topic\" = 'docinfo' AND \"mode\" = 'Ds' AND frequency =~ /^$frequency$/)  AND $timeFilter GROUP BY time($__interval), \"frequency\" fill(null)",
     "select": [
      [
       { "params": [ "corrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "docinfo" },
      { "condition": "AND", "key": "mode", "operator": "=", "value": "Ds" }
     ]
    }
   ]
  },
  {
   "title": "Download Channel Count and Modulation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT count(\"powerLevel\") FROM \"fb\" WHERE (\"mode\" = 'Us') AND $timeFilter GROUP BY time(5m), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "powerLevel" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "mode", "operator": "=", "value": "Ds" }
     ]
    }
   ]
  },
  {
   "title": "Upload Channel Count and Modulation",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "$tag_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT count(\"powerLevel\") FROM \"fb\" WHERE (\"mode\" = 'Us') AND $timeFilter GROUP BY time(5m), \"type\" fill(null)",
     "select": [
      [
       { "params": [ "powerLevel" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "mode", "operator": "=", "value": "Us" }
     ]
    }
   ]
  }
 ]
}