{
 "title": "Retentention Policy",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "auto $tag_device + 20",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT mean(\"Temperature\") FROM \"devices\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+ 20" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=", "value": "fb" }
     ]
    },
    {
     "alias": "m $tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "devices",
     "query": "SELECT mean(\"Temperature\") FROM \"devices\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=", "value": "fb" }
     ]
    }
   ]
  },
  {
   "title": "dnscache",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "auto $tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dnscache",
     "select": [
      [
       { "params": [ "hits_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "server::tag", "operator": "=", "value": "fb" }
     ]
    },
    {
     "alias": "m $tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "dnscache",
     "select": [
      [
       { "params": [ "hits_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "server::tag", "operator": "=", "value": "fb" }
     ]
    }
   ]
  },
  {
   "title": "docinfo",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "auto $tag_channelID + 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channelID::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fb_docinfo",
     "select": [
      [
       { "params": [ "corrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" },
       { "params": [ " + 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "channelID::tag", "operator": "=", "value": "1" }
     ]
    },
    {
     "alias": "m $tag_channelID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "channelID::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "fb_docinfo",
     "select": [
      [
       { "params": [ "corrErrors" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "channelID::tag", "operator": "=", "value": "1" }
     ]
    }
   ]
  },
  {
   "title": "ping",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "alias": "autogen + 1",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " +30" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "target::tag", "operator": "=", "value": "2a02:8100:6:2::311" }
     ]
    },
    {
     "alias": "m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ping",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "target::tag", "operator": "=", "value": "2a02:8100:6:2::311" }
     ]
    },
    {
     "alias": "m",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tmp",
     "select": [
      [
       { "params": [ "rtt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " +2" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "target::tag", "operator": "=", "value": "192.168.176.1" }
     ]
    }
   ]
  },
  {
   "title": "snmp",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "alias": "auto $tag_ifIndex + 100",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifIndex::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "etherStatsMulticastPkts_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "+ 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "ifIndex::tag", "operator": "=", "value": "7" }
     ]
    },
    {
     "alias": "m $tag_ifIndex",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "ifIndex::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "snmp",
     "select": [
      [
       { "params": [ "etherStatsMulticastPkts_count" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "10s" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "ifIndex::tag", "operator": "=", "value": "7" }
     ]
    }
   ]
  },
  {
   "title": "speedtest",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "alias": "auto $col * 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface_macAddr" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "upload_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "* 8 * 2" ], "type": "math" },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface_macAddr::tag", "operator": "=", "value": "48:0F:CF:C2:FC:66" }
     ]
    },
    {
     "alias": "m $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "interface_macAddr" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speedtest",
     "select": [
      [
       { "params": [ "upload_bandwidth" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" },
       { "params": [ "Upload" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "interface_macAddr::tag", "operator": "=", "value": "48:0F:CF:C2:FC:66" }
     ]
    }
   ]
  },
  {
   "title": "fb tr069",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "alias": "auto Down *2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fb_tr069",
     "select": [
      [
       { "params": [ "v_NewNumberOfEntries" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8  *2" ], "type": "math" }
      ]
     ]
    },
    {
     "alias": "m Down",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "fb_tr069",
     "select": [
      [
       { "params": [ "v_NewNumberOfEntries" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*8" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "sensors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "targets": [
    {
     "alias": "auto $tag_device + 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "Temp_int" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=", "value": "abseite" }
     ]
    },
    {
     "alias": "m $tag_device",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device::tag" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "Temp_int" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "device::tag", "operator": "=", "value": "abseite" }
     ]
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "alias": "auto $col + 10",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "m $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_idle" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "+10" ], "type": "math" }
      ]
     ]
    }
   ]
  }
 ]
}