{
 "title": "SensorInternal",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "measurement",
    "query": "SHOW SERIES WHERE \"topic\"='strom'"
   },
   {
    "name": "sensor",
    "label": "Sensor",
    "query": "SHOW TAG VALUES FROM sensors WITH KEY=topic"
   },
   {
    "name": "field",
    "label": "Common Filed",
    "query": "Heap, LoadAvg, MqttCount, Sleep, UptimeSec"
   }
  ]
 },
 "panels": [
  {
   "title": "$field",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "[[tag_topic]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT mean($field) FROM /^$measurement$/ WHERE (\"topic\" =~ /^$sensor$/) AND $timeFilter GROUP BY time($__interval), \"topic\" fill(none)",
     "select": [
      [
       { "params": [ "$field" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "alias": "[[tag_topic]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT mean(\"LoadAvg\") FROM \"sensors\" WHERE (\"topic\" =~ /^$sensor$/) AND $timeFilter GROUP BY time($__interval), \"topic\" fill(none)",
     "select": [
      [
       { "params": [ "UptimeSec" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "[[tag_topic]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "Wifi_RSSI" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Wifi Signal",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "targets": [
    {
     "alias": "[[tag_topic]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "Wifi_Signal" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5" ], "type": "moving_average" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  },
  {
   "title": "Vcc",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 20, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "[[tag_topic]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "Vcc" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=~", "value": "/^$sensor$/" }
     ]
    },
    {
     "alias": "[[tag_topic]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "sensors",
     "select": [
      [
       { "params": [ "Battery" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       {
        "params": [
         10
        ],
        "type": "moving_average"
       },
       { "params": [ " / 100 * 3" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=~", "value": "/^$sensor$/" }
     ]
    }
   ]
  }
 ]
}