{
 "title": "Smart",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "measurement", "query": { "query": "SHOW  MEASUREMENTS " } },
   {
    "name": "host",
    "query": {
     "query": "SHOW TAG VALUES FROM $measurement WITH KEY = \"host\""
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "health",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "health_ok" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Cycles",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "smartctl_attributes",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name::tag", "operator": "=", "value": "Power_Cycle_Count" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "smartctl",
     "select": [
      [
       { "params": [ "power_cycles" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Reallocated",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "smartctl_attributes",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name::tag", "operator": "=", "value": "Reallocated_Sector_Ct" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "smartctl",
     "select": [
      [
       { "params": [ "critical_comp_time" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Erase Fail",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "smartctl_attributes",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name::tag", "operator": "=", "value": "Erase_Fail_Count" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "smartctl",
     "select": [
      [
       { "params": [ "critical_warning" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Perc Used",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "percentage_used" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Available",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "smartctl_attributes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "Perc_Avail_Resrvd_Space" }
     ]
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "available_spare" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Power On",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "power_on_hours" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Capa",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "capacity" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Power Loss",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "smartctl_attributes",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "name::tag", "operator": "=", "value": "Unexpect_Power_Loss_Ct" },
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "host::tag" ], "type": "tag" }
     ],
     "measurement": "smartctl",
     "select": [
      [
       { "params": [ "unsafe_shutdowns" ], "type": "field" }
      ]
     ],
     "tags": [
      { "condition": "AND", "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "LBAs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "$tag_host: write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl_attributes",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "Total_LBAs_Written" }
     ]
    },
    {
     "alias": "$tag_host: read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl_attributes",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "Total_LBAs_Read" }
     ]
    },
    {
     "alias": "$tag_host: write",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl",
     "select": [
      [
       { "params": [ "data_units_written" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "$tag_host: read",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl",
     "select": [
      [
       { "params": [ "data_units_read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" },
       { "params": [ "* -1" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  },
  {
   "title": "Spare",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "alias": "$tag_host: avail spare ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl",
     "select": [
      [
       { "params": [ "available_spare" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "$tag_host: avail spare ",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl_attributes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "Perc_Avail_Resrvd_Space" }
     ]
    }
   ]
  },
  {
   "title": "Erase Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl_attributes",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "hp" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "Total_Write/Erase_Count" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl_attributes",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "hp" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "Avg_Write/Erase_Count" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl_attributes",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "5m" ], "type": "non_negative_derivative" }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=", "value": "hp" },
      { "condition": "AND", "key": "name::tag", "operator": "=", "value": "Perc_Write/Erase_Count" }
     ]
    }
   ]
  },
  {
   "title": "Spare",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "read $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl",
     "select": [
      [
       { "params": [ "data_units_read" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "write $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl",
     "select": [
      [
       { "params": [ "data_units_written" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spare",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "alias": "read $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl",
     "select": [
      [
       { "params": [ "host_reads" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "write $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl",
     "select": [
      [
       { "params": [ "host_writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Spare",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "alias": "$tag_host:$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "name::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl_attributes",
     "select": [
      [
       { "params": [ "raw_value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    },
    {
     "alias": "write $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host::tag" ], "type": "tag" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "smartctl",
     "select": [
      [
       { "params": [ "host_writes" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host::tag", "operator": "=~", "value": "/^$host$/" }
     ]
    }
   ]
  }
 ]
}