{
 "title": "Temperature",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "influxdb" },
   {
    "name": "rp",
    "query": {
     "query": "select time,rp from forever.grafana_rp where time > now() - ${__from}ms order by time asc limit 1"
    }
   },
   {
    "name": "measurement",
    "query": {
     "query": "SHOW SERIES WHERE \"device\"='sensor'"
    }
   },
   { "name": "interval", "query": "5m,1h" }
  ]
 },
 "panels": [
  {
   "title": "DewPoint Faust",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "[[tag_device]]-[[tag_source]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "topic" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT mean(\"Temperature\")-((100 - mean(\"Humidity\")) / 5)\n FROM $rp./^$measurement$/ WHERE $timeFilter GROUP BY time($__interval), \"device\", \"source\"",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "DewPoint Tasmota",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "[[tag_device]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device::tag" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "query": "SELECT exp(mean(\"Temperature\"))    FROM /^$measurement$/ WHERE $timeFilter GROUP BY time($__interval), \"topic\"",
     "select": [
      [
       { "params": [ "DewPoint" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Temperatur",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "[[tag_device]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "device::tag" ], "type": "tag" }
     ],
     "measurement": "/^$measurement$/",
     "select": [
      [
       { "params": [ "Temperature" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}