# /usr/bin/telegraf -config /etc/telegraf/telegraf_logs.conf
[agent]
# ohne: host=da4b3ace981f[,hostname=probook]
# hostname: host=probook,hostname=probook
# omit: hostname=probook (weil hostname durch ggf durch input)
  #hostname = "${AGENT_HOSTNAME}"  # sets host
  omit_hostname = true
  interval = "1m"
  round_interval = true
  metric_batch_size = 200
  metric_buffer_limit = 500
  collection_jitter = "0s"
  flush_interval = "1m"
  flush_jitter = "0s"
  precision = "1s"
  debug = true
  quiet = false
  #debug = false
  #quiet = true
  logfile = ""
  skip_processors_after_aggregators = true

[[processors.defaults]]
  namepass = ["logs", "docker_log"]
  order = 1
  [processors.defaults.tags]
    host = "${AGENT_HOSTNAME}"

[[processors.rename]]
  namepass = ["logs", "docker_log"]
  order = 2
  [[processors.rename.replace]]
    tag = "host"
    dest = "hostname"
