- platform: wake_on_lan
  name: pc
  mac: !secret mac_dt
#- platform: wake_on_lan
#  name: lg
#  mac: !secret mac_lgtv
#  turn_off:
#     service: media_player.turn_off
#     entity_id: media_player.tv

