[[inputs.tail]]
  # silently doing nothing is file nonexisting
  files = ["/hostfs/var/log/mosquitto/mosquitto.log"]

# debug
  # files = ["/tmp/input/mosquitto.log"]
  # initial_read_offset = "beginning"

  data_format = "grok"
  grok_patterns = ["^%{NUMBER:timestamp}: %{GREEDYDATA:message}"]
  name_override = "logs"
  # done globally
  #[inputs.tail.tags]
  #  host = "${AGENT_HOSTNAME}"
[[processors.converter]]
  namepass = ["logs"]
  [processors.converter.fields]
    timestamp = ["timestamp"]
    timestamp_format = "unix"
[[processors.regex]]
  namepass = ["logs"]
  order = 1
  [[processors.regex.tags]]
    key = "path"
    pattern = "^.*/([^.]+)(\\.log)?"
    replacement = "${1}"
[[processors.rename]]
  namepass = ["logs"]
  order = 2
  [[processors.rename.replace]]
    tag = "path"
    dest = "appname"
