# platform mqtt cannot be converted to light
- platform: mqtt
  name: "Dimmer"
  command_topic: "tasmota/tv/cmnd/POWER"
  state_topic: "tasmota/tv/tele/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tasmota/tv/tele/LWT"
  brightness_command_topic: "tasmota/tv/cmnd/Dimmer"
  brightness_state_topic: "tasmota/tv/tele/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false
# HA sendet Dimmer:100 das will die nicht
- platform: mqtt
  # Addressable LED
  name: "Vase"
  command_topic: "tasmota/rgb/cmnd/POWER"
  state_topic: "tasmota/rgb/stat/STATE"
  state_value_template: "{{value_json.POWER}}"
  availability_topic: "tasmota/rgb/tele/LWT"
  brightness_command_topic: "tasmota/rgb/cmnd/Dimmer"
  brightness_state_topic: "tasmota/rgb/stat/STATE"
  brightness_scale: 100
  on_command_type: "brightness"
  brightness_value_template: "{{value_json.Dimmer}}"
  rgb_command_topic: "tasmota/rgb/cmnd/Color2"
  rgb_state_topic: "tasmota/rgb/tele/STATE"
  rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
  effect_command_topic: "tasmota/rgb/cmnd/Scheme"
  effect_state_topic: "tasmota/rgb/stat/STATE"
  effect_value_template: "{{value_json.Scheme}}"
  effect_list:
  - 0
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
  - 7
  - 8
  - 9
  - 10
  - 11
  - 12
  payload_on: "ON"
  payload_off: "OFF"
  payload_available: "Online"
  payload_not_available: "Offline"
  qos: 1
  retain: false

