binary_sensor:
  - name: "Terrassentür"
    unique_id: "0x00158d000309b98b_contact_zigbee"
    state_topic: "zigbee/terrasse"
    json_attributes_topic: "zigbee/terrasse"
    value_template: "{{ value_json.contact }}"
    payload_on: "open"
    payload_off: "closed"
    availability:
    - topic: "tasmota/zigbee/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
    device:
      identifiers:
      - "zigbee_0x00158d000309b98b"
      name: "AqaraDoor"
      model: "Aqara door & window contact sensor (MCCGQ11LM)"
      manufacturer: "Xiaomi"
    device_class: door   # also: window, garage_door or opening
  - name: "FlurMotion"
    unique_id: "0x00158d0002f2a43c_occupancy_zigbee"
    state_topic: "zigbee/motion"
    json_attributes_topic: "zigbee/motion"
    value_template: "{{ value_json.motion }}"
    payload_on: "on"
    payload_off: "off"
    availability:
    - topic: "tasmota/zigbee/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
    device:
      identifiers:
      - "zigbee_0x00158d0002f2a43c"
      name: "AqaraMove"
      model: "Aqara human body movement and illuminance sensor (RTCGQ11LM)"
      manufacturer: "Xiaomi"
    device_class: motion

# ok braucht on und off
  - name: "Node-RED"
    state_topic: "lwt/node-red"
    payload_on: "Online"
    payload_off: "Offline"
    #value_template: "{% if is_state(entity_id,\"Online\")-%}ON{%-else-%}OFF{%-endif%}"

switch:
  - name: "Funk Socket 1"
    unique_id: "rev8342lc_sw_1"
    command_topic: "omg/bridge/commands/MQTTtoPilight"
    payload_on: '{"message":"{\"id\":15790320,\"unit\":1,\"on\":1}","protocol":"arctech_switch"}'
    payload_off: '{"message":"{\"id\":15790320,\"unit\":1,\"off\":1}","protocol":"arctech_switch"}'
    availability:
    - topic: "omg/bridge/LWT"
    device:
      identifiers:
      - "rev8342lc.1"
# wird ignoriert:
      suggested_area: "Wohnzimmer"
  - name: "Funk Socket 2"
    unique_id: "rev8342lc_sw_2"
    command_topic: "omg/bridge/commands/MQTTtoPilight"
    payload_on: '{"message":"{\"id\":15790320,\"unit\":2,\"on\":1}","protocol":"arctech_switch"}'
    payload_off: '{"message":"{\"id\":15790320,\"unit\":2,\"off\":1}","protocol":"arctech_switch"}'
    availability:
    - topic: "omg/bridge/LWT"
  - name: "Funk Socket ALL"
    unique_id: "rev8342lc_sw_all"
    command_topic: "omg/bridge/commands/MQTTtoPilight"
    payload_on: '{"message":"{\"id\":15790320,\"all\":1,\"on\":1}","protocol":"arctech_switch"}'
    payload_off: '{"message":"{\"id\":15790320,\"all\":1,\"off\":1}","protocol":"arctech_switch"}'
    availability:
    - topic: "omg/bridge/LWT"

# example
#  - name: "Tasmota Switch 1"
#    state_topic: "tasmota/kerze/stat/POWER"
#    value_template: "{{ value_json.POWER }}"
#    command_topic: "tasmota/kerze/cmnd/POWER"
#    payload_on: "ON"
#    payload_off: "OFF"
#    availability_topic: "tasmota/kerze/tele/LWT"
#    payload_available: "Online"
#    payload_not_available: "Offline"

#  qos: 1
#  retain: false

sensor:
  - name: "Keller Strom Battery"
    unique_id: "sensor.mt681_battery_level"
    state_topic: "tasmota/strom/tele/STATE"
    unit_of_measurement: "%"
    # 3.1-3.4
    value_template: "{{ ((value_json.Vcc | float(-1) - 3.1) * 333) | round() }}"
    device_class: battery

#tasmota/strom/tele/STATE {"Time":"2022-01-21T00:03:13","Uptime":"0T00:00:09","UptimeSec":9,"Vcc":3.366,"Heap":24,"SleepMode":"Dynamic","Sleep":50,"LoadAvg":19,"MqttCount":1,"Wifi":{"AP":1,"SSId":"BaseLAN","BSSId":"2C:67:FB:57:17:AC","Channel":6,"Mode":"11n","RSSI":32,"Signal":-84,"LinkCount":1,"Downtime":"0T00:00:03"}}

# Overwrite Deepsleep -> no availability
#  - name: "Sensor Temperatur"
#    unique_id: "sensor.sensor_bme680_temperature"
#    state_topic: "tasmota/sensor/tele/SENSOR"
#    value_template: "{{ value_json['BME680'].Temperature }}"
#    unit_of_measurement: "°C"
#    device_class: temperature
#    availability:
#    - topic: "tasmota/sensor/tele/LWT"
#      payload_available: "Online"
#      payload_not_available: "Offline"
#  - name: "Sensor Luftfeuchte"
#    unique_id: "sensor.sensor_bme680_humidity"
#    state_topic: "tasmota/sensor/tele/SENSOR"
#    value_template: "{{ value_json['BME680'].Humidity }}"
#    unit_of_measurement: "%"
#    device_class: humidity
#    availability:
#    - topic: "tasmota/sensor/tele/LWT"
#      payload_available: "Online"
#      payload_not_available: "Offline"
#  - name: "Sensor Luftdruck"
#    unique_id: "sensor.sensor_bme680_pressure"
#    state_topic: "tasmota/sensor/tele/SENSOR"
#    value_template: "{{ value_json['BME680'].Pressure }}"
#    unit_of_measurement: "hPa"
#    device_class: pressure
#    availability:
#    - topic: "tasmota/sensor/tele/LWT"
#      payload_available: "Online"
#      payload_not_available: "Offline"
#  - name: "Sensor Licht"
#    unique_id: "sensor.sensor_tls2561_.illuminance"
#    state_topic: "tasmota/sensor/tele/SENSOR"
#    value_template: "{{ value_json['TSL2561'].Illuminance }}"
#    unit_of_measurement: "lx"
#    device_class: illuminance
#    availability:
#    - topic: "tasmota/sensor/tele/LWT"
#      payload_available: "Online"
#      payload_not_available: "Offline"
#  - name: "Sensor interne Temperatur"
#    unique_id: "sensor.sensor_esp32_temperature"
#    state_topic: "tasmota/sensor/tele/SENSOR"
#    value_template: "{{ value_json['ESP32'].Temperature }}"
#    unit_of_measurement: "°C"
#    device_class: temperature
#    availability:
#    - topic: "tasmota/sensor/tele/LWT"
#      payload_available: "Online"
#      payload_not_available: "Offline"

# zigbee does not autodiscover
  - name: "Zigbee Controller Battery Level"
    unique_id: "sensor.zigbee_controller_battery_level"
    state_topic: "tasmota/zigbee/tele/STATE"
    unit_of_measurement: '%'
    value_template: "{{ ((value_json.Vcc | float(-1) - 3.3) * 600) | round() }}"
    device_class: battery
    availability:
    - topic: "tasmota/zigbee/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

# issue is bug in tasmota RSS should be dBm
  - name: "Wi-Fi Quality"
    unique_id: "sensor.tasmota.wifi.rssi"
    state_topic: "tasmota/kerze/tele/STATE"
    unit_of_measurement: "dBm"
    value_template: "{{ value_json['Wifi'].Signal }}"
    device_class: signal_strength
    availability:
    - topic: "tasmota/kerze/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"

# Track Firmware
  - name: "Tasmota Firmware"
    unique_id: "sensor.tasmota.firmware"
    state_topic: "tasmota/flur/stat/STATUS2"
    value_template: "{{value_json['StatusFWR'].Version }}"
    availability:
    - topic: "tasmota/flur/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
    qos: 0

light:
  - name: "Tripod"
    schema: template
    unique_id: "light.zigbee_tripod_0xec1bbdfffeae209a"
    command_topic: "tasmota/zigbee/cmnd/ZbSend"
    command_on_template: '{"Device":"Tripod","Send":{"Power":"ON"}}'
    command_off_template: '{"Device":"Tripod","Send":{"Power":"OFF"}}'
    state_topic: "zigbee/tripod/stat/POWER"
    state_template: "{{ value.lower() }}"
#    brightness_command_topic: "tasmota/Dimmer"
#    brightness_state_topic: "tele/tasmota/STATE"
#    brightness_scale: 100
#    on_command_type: "brightness"
#    brightness_value_template: "{{ value_json.Dimmer }}"
    availability:
    - topic: "tasmota/zigbee/tele/LWT"
      payload_available: "Online"
      payload_not_available: "Offline"
