- id: '1549980351867'
  alias: Raster
  description: automatischer trigger alle 5 min
  mode: single
  triggers:
  - trigger: time_pattern
    minutes: /5
  conditions: []
  actions:
  - action: mqtt.publish
    data:
      payload: raster from hp homeasssistent at {{ now() }}
      topic: test/topic
- id: '1665511011214'
  alias: Notify Internet
  description: Notify LG when Internet is gone
  mode: single
  triggers:
  - trigger: mqtt
    topic: test/monitor/inet
  conditions: []
  variables:
    notification_action: notify.lg_webos_tv_uj6309
    message: 'Internet {{ trigger.payload_json[''server''] }}: {{ trigger.payload_json[''error'']
      }}'
  actions:
  - action: '{{ notification_action }}'
    data:
      message: '{{ message }}'
- id: '1640877499206'
  alias: Kein Internet
  description: ''
  mode: single
  triggers:
  - trigger: state
    entity_id:
    - binary_sensor.reimers6660_wan_status
    to: 'on'
  conditions: []
  actions:
  - action: notify.lg_webos_tv_uj6309
    data:
      message: Internet offline
- id: '1592816091306'
  alias: Reimer Mqtt Test
  description: wenn irgendeine Nachricht kommt
  mode: single
  triggers:
  - trigger: mqtt
    topic: test/monitor/test
  conditions: []
  actions:
  - action: persistent_notification.create
    data:
      title: Inet Status
      message: '# Inet Status

        Your message goes *here* {{ trigger.payload_json[''server''] }}

        '
      notification_id: inet_state_notification
- id: notify_flur_tv
  alias: Notify on Status
  description: Notify when mqtt message arrives
  mode: single
  triggers:
  - trigger: state
    entity_id:
    - switch.tasmotaflur_flur
    to:
    - 'on'
  conditions: []
  actions:
  - action: notify.lg_webos_tv_uj6309
    data:
      message: Flur Licht angegangen
- id: b4a6eeee95f943f38b2fda58ef067cb4
  alias: Tasmota Firmware Version Check
  triggers:
  - trigger: homeassistant
    event: start
  actions:
  - action: mqtt.publish
    data:
      topic: groups/tasmotas/cmnd/STATUS
      payload: '2'
- id: 92c5adbf2e9443fc98fbb2be6c231ea4
  alias: Backup Home Assistant every night at 3 AM
  description: ''
  mode: single
  triggers:
  - trigger: time
    at: 03:00:00
  actions:
  - action: backup.create
    metadata: {}
    data: {}
- alias: Wake-me up using bedroom lights
  trigger:
    platform: template
    value_template: '{{ states(''sensor.time'') == (states.input_datetime.wakeup_time.attributes.timestamp
      | int | timestamp_custom(''%H:%M'', False)) }}'
  condition:
  - condition: state
    entity_id: input_boolean.wakeup_enabled
    state: 'on'
  - condition: or
    conditions:
    - condition: state
      entity_id: input_boolean.wakeup_weekend
      state: 'on'
    - condition: time
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
  - service: light.turn_on
    entity_id: group.bedroom
    data:
      transition: 600
      brightness: 255
  id: 4db819644f234463ac35152c956b9d78
- id: '1640869317480'
  alias: TV auf PC
  description: ''
  trigger: []
  condition:
  - condition: state
    entity_id: input_boolean.pc_gaming
    state: 'on'
  action:
  - service: media_player.select_source
    target:
      entity_id: media_player.lg_webos_tv_uj6309
    data:
      source: PC
  - service: switch.turn_on
    target:
      entity_id: switch.pc
- id: '1660755876743'
  alias: LG webOS Smart TV - Turn On Action
  description: ''
  use_blueprint:
    path: cvroque/webostv_turn_on.yaml
    input:
      webostv: media_player.lg_webos_tv_uj6309
      webostv_mac: DC-4F-22-F8-F5-77
- id: '1665249726951'
  alias: Package Lost
  description: Note when ping loss is > 90
  trigger:
  - platform: mqtt
    topic: metrics/ping/2a02_8100_6_2__311
    value_template: '{{ value_json[''ping''][''pl''] }}'
  condition: []
  action:
  - service: persistent_notification.create
    data:
      title: Package Loss
      message: '# Ping Loss

        {{ trigger.topic }} is {{ trigger.payload_json[''ping''][''pl''] }}

        '
      notification_id: package_loss_notification
  mode: single
- id: '1729109608364'
  alias: Handy Laden
  description: ''
  mode: single
  triggers:
  - trigger: numeric_state
    entity_id:
    - sensor.sm_s921b_battery_level
    below: 10
  conditions: []
  actions:
  - action: notify.lg_webos_tv_uj6309
    data:
      message: Handy Laden
#- alias: Alexa Announce
#  id: alexa_announce
#  triggers:
#  - platform: state
#    entity_id: person.reimer
#    to: home
#  actions:
#  - action: notify.send_message
#    data:
#      message: Welcome home Reimer
#    target:
#      entity_id: notify.reiners_echo_dot_durchsagen
- alias: "test mqtt trigger"
  id: tv_power_on
  mode: single
  triggers:
  - trigger: mqtt
    options:
      topic: tasmota/tv/stat/POWER
      payload: 'OFF'
  conditions: []
  actions:
  - action: notify.lg_webos_tv_uj6309
    data:
      message: BG off
- id: auto.alexa_quiet_on
  alias: Alexa ruhig
  mode: single
  triggers:
  - trigger: time
    at: 01:00:00
  actions:
  - action: switch.turn_on
    target:
      entity_id: switch.reiners_echo_dot_bitte_nicht_storen
- id: auto.alexa_quiet_off
  alias: Alexa an
  mode: single
  triggers:
  - trigger: time
    at: 08:00:00
  actions:
  - action: switch.turn_off
    target:
      entity_id: switch.reiners_echo_dot_bitte_nicht_storen

