- unique_id: sensor_schlaf_absolute_humidity_0001
  use_blueprint:
    path: absolute_humidity.yaml
    input:
      reference_temp: sensor.tasmotaschlaf_bme280_temperature
      reference_humi: sensor.tasmotaschlaf_bme280_humidity
- unique_id: sensor_schlaf_bt_absolute_humidity_0001
  use_blueprint:
    path: absolute_humidity.yaml
    input:
      reference_temp: sensor.schlaftemperatur
      reference_humi: sensor.schlaffeuchtigkeit
- unique_id: sensor_bad_absolute_humidity_0001
  use_blueprint:
    path: absolute_humidity.yaml
    input:
      reference_temp: sensor.bad_temperatur
      reference_humi: sensor.bad_luftfeuchtigkeit
# muell
#- unique_id: sensor_bad_bt_absolute_humidity_0001
#  use_blueprint:
#    path: absolute_humidity.yaml
#    input:
#      reference_temp: sensor.atc_edc2_temperature
#      reference_humi: sensor.atc_edc2_humidity
- unique_id: sensor_abseite_bt_absolute_humidity_0001
  use_blueprint:
    path: absolute_humidity.yaml
    input:
      reference_temp: sensor.thb2_8af6_temperatur
      reference_humi: sensor.thb2_8af6_luftfeuchtigkeit
- unique_id: sensor_kueche_bt_absolute_humidity_0001
  use_blueprint:
    path: absolute_humidity.yaml
    input:
      reference_temp: sensor.tasmotasensor_bme680_temperature
      reference_humi: sensor.tasmotasensor_bme680_humidity
- unique_id: sensor_wohn_bt_absolute_humidity_0001
  use_blueprint:
    path: absolute_humidity.yaml
    input:
      reference_temp: sensor.thb1_wohn_2728_temperatur
      reference_humi: sensor.thb1_wohn_2728_luftfeuchtigkeit
- unique_id: sensor_rtl433_absolute_humidity_0001
  use_blueprint:
    path: absolute_humidity.yaml
    input:
      reference_temp: sensor.rtl433_aussensensor_temperature
      reference_humi: sensor.rtl433_aussensensor_humidity
- unique_id: sensor_openweather_absolute_humidity_0001
  use_blueprint:
    path: absolute_humidity.yaml
    input:
      reference_temp: weather.forecast_home.temperature
      reference_humi: weather.forecast_home.humidity
- unique_id: sensor_openweather_forecast_absolute_humidity_0001
  use_blueprint:
    path: absolute_humidity.yaml
    input:
      reference_temp: sensor.openweathermap_forecast_temperature
      reference_humi: sensor.openweathermap_humidity

- sensor:
#tasmota_ble/tele/bad {"Time":"2022-01-20T23:40:57","alias":"bad","mac":"a4c138e4edc2","Temperature":22.6,"Humidity":65.0,"DewPoint":15.7,"Battery":57,"RSSI":-83}
# https://community.home-assistant.io/t/alert-when-devices-have-low-battery/258072
# select('ge', 0) b4 list
  - name: 'Devices with low battery'
    default_entity_id: sensor.devices_with_low_battery
    unit_of_measurement: devices
    state: >-
      {% set ignore_entities = ['sensor.phone_1_battery_level', 'sensor.phone_2_battery_level', '...'] %}
      {{ states.sensor
         | selectattr('attributes.device_class', 'defined')
         | selectattr('attributes.device_class', 'eq', 'battery')
         | rejectattr('entity_id', 'in', ignore_entities)
         | map(attribute='state')
         | reject('in', ['unknown', 'unavailable', 'Ok'])
         | map('int', -1) | select('le', 10)
         | list | count
      }}
    icon: >-
      {% if is_state('sensor.devices_with_low_battery', '0') %}
        mdi:check-circle
      {% else %}
        mdi:battery-alert
      {% endif %}

#  - weather:
#    #pressure: "{{ states('sensor.sensor_luftdruck') | float(0) }}"
#    #temperature: "{{ states('sensor.rtl433_aussensensor_temperatur') | float(0) }}"
#  #  forecast: "{{ state_attr('weather.openweathermap', 'forecast') }}"

# 'condition_template'
- weather:
  - name: Aussenwetter
    unique_id: weather.aussenwetter
    condition_template: '{{ states(''weather.openweathermap'') }}'
    humidity_template: '{{ states(''sensor.rtl433_aussensensor_luftfeuchtigkeit'') | float(0)
      }}'
    temperature_template: '{{ states(''sensor.rtl433_aussensensor_temperatur'') | float(0)
      }}'

